server:
  port: 80
  servlet:
    context-path: /TechWorld
spring:
#  datasource:
#    password: Nam@135792002
#    url: jdbc:mysql://localhost:3306/techworld_db
#    username: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#        format_sql: true
#    show_sql: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 664247552092-7o9gcg0bcbt2qqshis9mc7uct2qrr0v9.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          facebook:
            client-id: 189090894274580
            client-secret: 7d08b05629b5a55b7a2075db3e1a67f5
            scope:
              - email
              - public_profile